{{- if and .Values.podDisruptionBudget.enabled (include "orrery-assistant.multiReplica" .) -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "orrery-assistant.fullname" . }}
  labels:
    {{- include "orrery-assistant.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "orrery-assistant.selectorLabels" . | nindent 6 }}
{{- end }}
