{{- if .Values.pubsubWorker.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orrery-assistant.pubsubWorker.fullname" . }}
  labels:
    {{- include "orrery-assistant.pubsubWorker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.pubsubWorker.replicaCount }}
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "orrery-assistant.pubsubWorker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "orrery-assistant.pubsubWorker.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if and (not .Values.existingSecret) .Values.secrets }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.pubsubWorker.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "orrery-assistant.pubsubWorker.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-pubsub-worker
          image: {{ include "orrery-assistant.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- toYaml .Values.pubsubWorker.command | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "orrery-assistant.fullname" . }}
            - secretRef:
                name: {{ include "orrery-assistant.secretName" . }}
          resources:
            {{- toYaml .Values.pubsubWorker.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: cache
              mountPath: /home/appuser/.cache
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 256Mi
        - name: cache
          emptyDir:
            sizeLimit: 512Mi
      {{- with .Values.pubsubWorker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pubsubWorker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pubsubWorker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
