{{- if and (not .Values.existingSecret) .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-assistant.fullname" . }}
  labels:
    {{- include "devops-assistant.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
