[project]
name = "kafka-health-agent"
version = "0.4.1"
description = "Agent for monitoring and managing Kafka cluster health"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "orrery-core",
    "confluent-kafka>=2.15.0",
    "kubernetes>=36.0.3",
]

[tool.uv.sources]
orrery-core = { workspace = true }

[build-system]
requires = ["setuptools>=84.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["kafka_health_agent*"]
